version: '3.8'
services:
  web:
    build: .
    ports:
    - "127.0.0.1:6001:5000"
    links:
    - mymongo
  mymongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
volumes:
  mongo-data:
  mongo-configdb:
