version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "127.0.0.1:6001:5000"
    links:
    - mymongo
    restart: unless-stopped
  cron:
    build:
      context: .
      dockerfile: Dockerfile
    links:
    - mymongo
    restart: unless-stopped
    entrypoint: cron -f -L3
  mymongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
      - mongo-backup:/data/backup
    restart: unless-stopped
volumes:
  mongo-data:
  mongo-configdb:
  mongo-backup:
